const translations = {
    fa: {
        kanun: "کانون",
        lion_sun: "شیر و خورشید",
        tagline: "خانه فرهنگ، زبان، تاریخ و هویت ایران",
        schild_assoc: "انجمن پادشاهی شیلد",
        welcome_msg: "به همه شما، با هر دین و باور و گویشی که هستید، پاکدلانه خوشامد می‌گوییم",
        intro_text: "جایی آرام، دنج و زیبا برای گردهمایی، گفتمان، خوانش، پژوهش و ایجاد پیوستگی میان انسان‌ها با فرهنگ‌ها و پیشینه‌های گوناگون.",
        features_title: "در خانه شیر و خورشید می‌توانید:",
        f1: "در محیطی آرام از قهوه، چای، نوشیدنی‌ها، کیک و میان‌وعده‌های سبک لذت ببرید.",
        f2: "در کلاس‌های آموزش زبان فارسی و آلمانی در فضایی صمیمی و دوستانه شرکت کنید.",
        f3: "در کتابخانه دنج انجمن مطالعه کنید و به نسخه‌های گران‌سنگ ادبیات پارسی دست یابید.",
        f4: "در شب‌های ادبی، شعرخوانی، شاهنامه‌خوانی، موسیقی و برنامه‌های هنری حضور یابید.",
        f5: "در نشست‌های فرهنگی، سمینارها و برنامه‌های آموزشی شرکت کنید.",
        f6: "از نمایشگاه‌های نقاشی، عکس و هنرهای تجسمی بازدید کنید و هنرمندان را حمایت کنید.",
        f7: "جلسات، دورهمی‌ها، جشن‌های کوچک، تولد و مناسبت‌های خصوصی خود را در فضایی زیبا برگزار کنید.",
        f8: "در جشن‌های ملی و فرهنگی ایران، آیین‌ها و مراسم سنتی همراه ما باشید.",
        f9: "با افراد جدید آشنا شوید و دوستی‌ها و پیوندهای تازه‌ای شکل دهید.",
        f10: "برنامه‌های فرهنگی و آموزشی ویژه کودکان و نوجوانان برگزار می‌شود.",
        about_p1: "خانه شیر و خورشید محلی برای پاسداری از فرهنگ، زبان و تاریخ ایران است.",
        about_p2: "ما باور داریم که فرهنگ و تاریخ ایران، میراث گران‌بهای هزاران ساله این سرزمین است که باید آن را شناخت، حفظ کرد و به نسل‌های آینده منتقل ساخت...",
        open_msg: "درهای ما به روی همه باز است.",
        bottom_quote: "فرهنگ، ریشه یک ملت است؛ زبان، جان آن؛ و تاریخ، حافظه آن.\nخانه شیر و خورشید، پاسدار این میراث جاودان است."
    },
    de: {
        kanun: "Zentrum",
        lion_sun: "Löwe und Sonne",
        tagline: "Haus der iranischen Kultur, Sprache, Geschichte und Identität",
        schild_assoc: "Königliche Vereinigung Schild",
        welcome_msg: "Wir heißen Sie alle, unabhängig von Religion, Glauben oder Sprache, herzlich willkommen.",
        intro_text: "Ein ruhiger, gemütlicher und schöner Ort für Zusammenkünfte, Diskurse, Forschung und Verbindung zwischen Menschen unterschiedlicher Herkunft.",
        features_title: "Im Haus von Löwe und Sonne können Sie:",
        f1: "Kaffee, Tee, Getränke und leichte Snacks in einer entspannten Atmosphäre genießen.",
        f2: "An Sprachkursen für Persisch und Deutsch in freundlicher Atmosphäre teilnehmen.",
        f3: "In der gemütlichen Bibliothek lesen und wertvolle persische Literatur entdecken.",
        f4: "An Literaturabenden, Musik- und Kunstveranstaltungen teilnehmen.",
        f5: "An kulturellen Treffen, Seminaren und Bildungsprogrammen teilnehmen.",
        f6: "Kunst- und Fotoausstellungen besuchen und Künstler unterstützen.",
        f7: "Ihre privaten Feiern, Geburtstage und Treffen veranstalten.",
        f8: "Traditionelle und nationale iranische Feste mit uns feiern.",
        f9: "Neue Leute kennenlernen und neue Freundschaften schließen.",
        f10: "Kultur- und Bildungsprogramme für Kinder und Jugendliche besuchen.",
        about_p1: "Das Haus Löwe und Sonne ist ein Ort zur Bewahrung der iranischen Kultur.",
        about_p2: "Wir glauben, dass die Kultur und Geschichte des Iran ein wertvolles Erbe ist...",
        open_msg: "Unsere Türen stehen allen offen.",
        bottom_quote: "Kultur ist die Wurzel einer Nation; Sprache ihre Seele; Geschichte ihr Gedächtnis."
    },
    en: {
        kanun: "Center of",
        lion_sun: "Lion and Sun",
        tagline: "House of Iranian Culture, Language, History and Identity",
        schild_assoc: "Schild Royal Association",
        welcome_msg: "We warmly welcome all of you, regardless of religion, belief, or dialect.",
        intro_text: "A peaceful, cozy, and beautiful place for gatherings, discussions, research, and building connections among people of diverse cultures.",
        features_title: "At the House of Lion and Sun, you can:",
        f1: "Enjoy coffee, tea, beverages, cakes, and light snacks in a calm atmosphere.",
        f2: "Join Persian and German language classes in a friendly setting.",
        f3: "Read in our cozy library and access precious Persian literary works.",
        f4: "Attend literary nights, poetry readings, music, and art events.",
        f5: "Participate in cultural meetings, seminars, and educational workshops.",
        f6: "Visit art and photography exhibitions and support artists.",
        f7: "Host your private meetings, small celebrations, and birthdays in a beautiful venue.",
        f8: "Celebrate national and cultural Iranian festivals with us.",
        f9: "Meet new people and build lasting friendships.",
        f10: "Participate in cultural programs dedicated to children and youth.",
        about_p1: "The House of Lion and Sun is a sanctuary for preserving Iranian culture.",
        about_p2: "We believe Iranian culture and history are precious millennial inheritances that must be preserved...",
        open_msg: "Our doors are open to everyone.",
        bottom_quote: "Culture is the root of a nation; language its soul; history its memory."
    }
};
