const translations = {
    fa: {
        kanun_title: "کانون شیر و خورشید",
        kanun_sub: "Haus der iranischen Kultur, Sprache, Geschichte und Identität",
        nav_about: "درباره ما",
        nav_services: "برنامه‌ها",
        nav_gallery: "رویدادها",
        nav_contact: "تماس با ما",
        hero_title: "کاشانه فرهنگ، زبان، تاریخ و هویت ایران",
        hero_sub: "Home of Iranian Culture, Language, History and Identity",
        welcome_btn: "خوش آمدید",
        about_title: "درباره ما",
        about_text: "کانون شیر و خورشید کاشانه فرهنگی، زبان، گفتمان و پژوهش برای گردهمایی پژوهشگران، علاقه‌مندان، اساتید و هنرمندان در محیطی صمیمی و دوستانه است.",
        services_title: "برنامه‌ها و خدمات",
        s1_title: "کافی‌شاپ و گفتگو",
        s1_desc: "فضایی آرام برای لذت بردن از قهوه و میان‌وعده.",
        s2_title: "کتابخانه و مطالعه",
        s2_desc: "دسترسی به ادبیات گران‌سنگ پارسی.",
        s3_title: "شب‌های ادبی و هنری",
        s3_desc: "موسیقی، شعرخوانی، شاهنامه‌خوانی.",
        s4_title: "نمایشگاه و کارگاه",
        s4_desc: "حمایت از هنرمندان و دوره‌های آموزشی.",
        gallery_title: "گالری تصاویر",
        contact_title: "ارتباط با ما",
        qr_text: "اسکن کنید برای اطلاعات بیشتر",
        schild_p1: "انجمن پادشاهی",
        footer_quote: "فرهنگ، ریشه یک ملت است؛ زبان، جان آن؛ و تاریخ، حافظه آن.\nخانه شیر و خورشید، پاسدار این میراث جاودان است."
    },
    de: {
        kanun_title: "Löwe und Sonne Zentrum",
        kanun_sub: "Haus der iranischen Kultur, Sprache, Geschichte und Identität",
        nav_about: "Über uns",
        nav_services: "Leistungen",
        nav_gallery: "Galerie",
        nav_contact: "Kontakt",
        hero_title: "Haus der iranischen Kultur, Sprache und Geschichte",
        hero_sub: "Home of Iranian Culture, Language, History and Identity",
        welcome_btn: "Willkommen",
        about_title: "Über uns",
        about_text: "Das Zentrum Löwe und Sonne ist ein Ort für Kultur, Sprache und Forschung, an dem sich Interessierte in einer freundlichen Atmosphäre treffen können.",
        services_title: "Unsere Angebote",
        s1_title: "Café & Gespräche",
        s1_desc: "Genießen Sie Kaffee und Snacks in ruhiger Atmosphäre.",
        s2_title: "Bibliothek & Lesen",
        s2_desc: "Zugang zu wertvoller persischer Literatur.",
        s3_title: "Literatur- & Kunstabende",
        s3_desc: "Musik, Poesie und Kulturveranstaltungen.",
        s4_title: "Ausstellungen",
        s4_desc: "Unterstützung von Künstlern und Workshops.",
        gallery_title: "Galerie",
        contact_title: "Kontakt",
        qr_text: "Scannen für mehr Informationen",
        schild_p1: "Königliche Vereinigung",
        footer_quote: "Kultur ist die Wurzel einer Nation; Sprache ihre Seele; Geschichte ihr Gedächtnis."
    },
    en: {
        kanun_title: "Lion and Sun Center",
        kanun_sub: "Haus der iranischen Kultur, Sprache, Geschichte und Identität",
        nav_about: "About Us",
        nav_services: "Services",
        nav_gallery: "Gallery",
        nav_contact: "Contact",
        hero_title: "Home of Iranian Culture, Language, History and Identity",
        hero_sub: "Home of Iranian Culture, Language, History and Identity",
        welcome_btn: "Welcome",
        about_title: "About Us",
        about_text: "The Lion and Sun Center is a sanctuary for culture, language, and research, bringing together scholars and enthusiasts in a warm environment.",
        services_title: "Services & Activities",
        s1_title: "Café & Dialogue",
        s1_desc: "A calm space to enjoy coffee and light snacks.",
        s2_title: "Library & Reading",
        s2_desc: "Access to Persian literary works.",
        s3_title: "Literary Nights",
        s3_desc: "Music, poetry reading, and cultural events.",
        s4_title: "Exhibitions & Workshops",
        s4_desc: "Supporting artists and hosting educational courses.",
        gallery_title: "Gallery",
        contact_title: "Contact Us",
        qr_text: "Scan for more info",
        schild_p1: "Schild Royal Association",
        footer_quote: "Culture is the root of a nation; language its soul; history its memory."
    }
};
